import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createAnalizlerScreenStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.background,
  },
  header: {
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  backBtn: {
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "700",
  },
  headerTitle: {
    flex: 1,
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  tabRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  tabBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnActive: {
    borderColor: "#ffd7b0",
    backgroundColor: palette.accent,
  },
  tabBtnText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "700",
  },
  tabBtnTextActive: {
    color: "#fff",
  },
  content: {
    padding: 12,
    gap: 10,
    paddingBottom: 24,
  },
  signalPage: {
    flex: 1,
    padding: 10,
  },
  signalCard: {
    flex: 1,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 8,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 8,
  },
  searchItem: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
    backgroundColor: palette.background,
  },
  searchItemActive: {
    borderColor: "#ffd7b0",
  },
  searchItemTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
  },
  searchItemSub: {
    color: palette.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  tfRow: {
    gap: 8,
    paddingVertical: 6,
    alignItems: "center",
  },
  tfBox: {
    borderWidth: 1,
    borderColor: "#1f5aa9",
    borderRadius: 8,
    backgroundColor: "#08245a",
    paddingHorizontal: 6,
    marginBottom: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: palette.background,
  },
  chipActive: {
    borderColor: "#ffd7b0",
    backgroundColor: palette.accent,
  },
  chipText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#fff",
  },
  signalText: {
    fontSize: 16,
    fontWeight: "800",
    marginTop: 2,
  },
  signalBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
    marginBottom: 8,
  },
  signalBadge: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: palette.background,
  },
  signalBadgeOnBuy: {
    borderColor: "#22c55e",
    backgroundColor: "rgba(34,197,94,0.2)",
  },
  signalBadgeOnSell: {
    borderColor: "#ef4444",
    backgroundColor: "rgba(239,68,68,0.2)",
  },
  signalBadgeText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "700",
  },
  chartCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.background,
    padding: 0,
    marginTop: 4,
    overflow: "hidden",
    marginHorizontal: -2,
  },
  chartViewport: {
    height: 360,
    minHeight: 360,
    width: "100%",
    backgroundColor: "#06143a",
  },
  webChart: {
    flex: 1,
    backgroundColor: "#06143a",
  },
  scoreBar: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1f5aa9",
    backgroundColor: "#08245a",
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginTop: 6,
  },
  scoreBarText: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "700",
  },
  scoreBarSubText: {
    color: "#bfdbfe",
    fontSize: 11,
    marginTop: 3,
    fontWeight: "600",
  },
  hint: {
    marginTop: 4,
    backgroundColor: palette.background,
    color: palette.textMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  bottomInfoBox: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#1f5aa9",
    borderRadius: 8,
    backgroundColor: "#08245a",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  bottomInfoText: {
    color: "#e2e8f0",
    fontSize: 12,
    fontWeight: "600",
  },
  rowLabel: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
  },
  input: {
    height: 40,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    color: palette.text,
    backgroundColor: palette.background,
    marginBottom: 8,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  searchInputInline: {
    flex: 1,
    marginBottom: 0,
  },
  searchBtnInline: {
    height: 40,
    minWidth: 78,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ffd7b0",
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtn: {
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ffd7b0",
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  searchBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  saveBtn: {
    height: 40,
    borderRadius: 10,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    alignSelf: "flex-start",
    paddingHorizontal: 26,
  },
  saveBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
  },
  subTitle: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  alarmRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    padding: 8,
    marginTop: 6,
    backgroundColor: palette.background,
  },
  removeBtn: {
    height: 30,
    minWidth: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  removeBtnText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
  },
  alarmInputRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  alarmInputLeft: {
    flex: 1.7,
  },
  alarmInputRight: {
    flex: 1,
  },
  chatIdInput: {
    height: 48,
    borderWidth: 1,
    borderColor: "#1f4a86",
    borderRadius: 16,
    paddingHorizontal: 14,
    color: "#e2e8f0",
    backgroundColor: "#0b2158",
    marginTop: 4,
  },
  telegramSaveBtn: {
    marginTop: 10,
    height: 52,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#2eb7ff",
    backgroundColor: "#081f57",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 28,
  },
  telegramSaveBtnText: {
    color: "#8ed7ff",
    fontSize: 18,
    fontWeight: "800",
  },
  telegramInfoCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#1f5aa9",
    backgroundColor: "#0a2b63",
    borderRadius: 16,
    padding: 12,
    flexDirection: "row",
    gap: 10,
  },
  telegramInfoTitle: {
    color: "#e2e8f0",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
  },
  telegramInfoText: {
    color: "#93c5fd",
    fontSize: 12,
    lineHeight: 17,
  },
  botOpenBtn: {
    alignSelf: "flex-start",
    borderWidth: 2,
    borderColor: "#31b3ff",
    borderRadius: 16,
    backgroundColor: "#0b2760",
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  botOpenBtnText: {
    color: "#cfeeff",
    fontSize: 15,
    fontWeight: "700",
  },
});
}
