import { Platform, StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createHomeStyles(colors: ThemePalette) {
  const CARD_BG = colors.background;
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    mainBody: {
      flex: 1,
      minHeight: 0,
      position: "relative",
    },
    mainScroll: {
      flex: 1,
      minHeight: 0,
    },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingTop: 5,
      paddingBottom: 7,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    profileButton: {
      width: 66,
      alignItems: "center",
    },
    profileImage: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: colors.border,
    },
    profileName: {
      marginTop: 2,
      fontSize: 10,
      color: colors.textMuted,
      fontWeight: "600",
    },
    titleWrap: {
      flex: 1,
      marginHorizontal: 10,
    },
    welcome: {
      fontSize: 11,
      color: colors.textMuted,
      marginBottom: 2,
      lineHeight: 15,
    },
    topActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    iconButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.primaryLight,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    iconText: {
      fontSize: 17,
    },
    settingsButton: {
      backgroundColor: colors.accent,
      borderColor: "#ffd7b0",
      borderWidth: 2,
    },
    settingsIconText: {
      fontSize: 18,
      color: "#ffffff",
      fontWeight: "700",
    },
    badge: {
      position: "absolute",
      top: -5,
      right: -5,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: "#ef4444",
      borderWidth: 1,
      borderColor: "#ffffff",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    badgeText: {
      color: "#ffffff",
      fontSize: 10,
      fontWeight: "600",
    },
    scrollContent: {
      paddingHorizontal: 12,
      paddingTop: 6,
      paddingBottom: 0,
    },
    heroCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 6,
    },
    topShortcutRow: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 4,
    },
    balanceRow: {
      flexDirection: "row",
      alignItems: "stretch",
      gap: 4,
      marginTop: 4,
    },
    topNavItem: {
      flex: 1,
      minWidth: 0,
      backgroundColor: CARD_BG,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingVertical: 4,
      paddingHorizontal: 4,
      height: 68,
      alignItems: "center",
      justifyContent: "center",
    },
    topNavItemActive: {
      backgroundColor: colors.accent,
      borderColor: "#ffd7b0",
    },
    topNavIcon: {
      fontSize: 18,
      color: colors.text,
    },
    walletMenOuter: {
      width: 28,
      height: 20,
      borderRadius: 4,
      borderWidth: 2,
      justifyContent: "center",
      alignItems: "center",
    },
    walletMenBar: {
      width: 15,
      height: 2,
      borderRadius: 1,
    },
    tileLabel: {
      marginTop: 2,
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: "500",
      textAlign: "center",
      lineHeight: 14,
    },
    tileLabelActive: {
      color: "#ffffff",
    },
    balanceCard: {
      flex: 1,
      minWidth: 0,
      backgroundColor: CARD_BG,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 8,
      paddingVertical: 4,
      height: 68,
    },
    kiyaslaCard: {
      width: "24%",
      minWidth: 0,
      backgroundColor: CARD_BG,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 6,
      paddingVertical: 4,
      height: 68,
      alignItems: "center",
      justifyContent: "center",
    },
    kiyaslaCardActive: {
      backgroundColor: colors.accent,
      borderColor: "#ffd7b0",
    },
    kiyaslaIconEmoji: {
      fontSize: 19,
      lineHeight: 21,
    },
    kiyaslaLabelOffset: {
      marginTop: 2,
    },
    balanceLabel: {
      fontSize: 13,
      color: colors.textMuted,
    },
    balanceValue: {
      marginTop: 2,
      fontSize: 17,
      fontWeight: "700",
      color: colors.text,
    },
    balanceChange: {
      marginTop: 2,
      fontSize: 11,
      color: colors.success,
      fontWeight: "700",
    },
    miniUp: {
      marginTop: 4,
      color: colors.success,
      fontSize: 12,
      fontWeight: "700",
    },
    miniDown: {
      marginTop: 4,
      color: colors.error,
      fontSize: 12,
      fontWeight: "700",
    },
    sectionCard: {
      marginTop: 6,
      backgroundColor: colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 7,
    },
    marketsSectionCard: {
      marginTop: 5,
      marginBottom: 4,
      paddingBottom: 12,
    },
    quickSectionCard: {
      marginTop: 5,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 5,
    },
    sectionTitleTight: {
      marginBottom: 0,
    },
    sectionTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 5,
    },
    tvRow: {
      flexDirection: "row",
    },
    tvRowBottom: {
      flexDirection: "row",
      marginTop: 4,
    },
    homeMarketCol: {
      flex: 1,
      minWidth: 0,
    },
    tvGapRight: {
      marginRight: 6,
    },
    quickGrid: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 4,
    },
    quickItem: {
      width: "24%",
      backgroundColor: CARD_BG,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 4,
      paddingHorizontal: 2,
      height: 66,
      alignItems: "center",
      justifyContent: "center",
    },
    quickItemIcon: {
      fontSize: 17,
      color: colors.accent,
      fontWeight: "700",
    },
    bottomBar: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surface,
      ...(Platform.OS === "android" ? { elevation: 16 } : {}),
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    tabItem: {
      alignItems: "center",
      justifyContent: "center",
      width: "19%",
      paddingVertical: 3,
      minHeight: 0,
    },
    tabIcon: {
      color: colors.textMuted,
      fontSize: 17,
    },
    tabText: {
      marginTop: 2,
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: "500",
      lineHeight: 12,
    },
    tabTextActive: {
      color: colors.accent,
    },
    tabItemCenter: {
      width: "19%",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 3,
      minHeight: 0,
    },
    tabCenterCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 2,
    },
    tabCenterPlus: {
      color: "#fff",
      fontSize: 24,
      lineHeight: 26,
      fontWeight: "700",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "flex-start",
      paddingTop: 82,
      paddingHorizontal: 14,
    },
    menuCard: {
      width: "88%",
      maxWidth: 360,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 10,
      zIndex: 1,
    },
    menuTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 8,
    },
    menuGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      rowGap: 6,
    },
    menuGridCell: {
      width: "48%",
      minHeight: 40,
      paddingVertical: 8,
      paddingHorizontal: 6,
      backgroundColor: CARD_BG,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    menuGridCellText: {
      fontSize: 11,
      color: colors.text,
      fontWeight: "600",
      textAlign: "center",
      lineHeight: 14,
    },
    menuLogoutButton: {
      marginTop: 10,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: colors.error,
      alignItems: "center",
      justifyContent: "center",
    },
    menuLogoutButtonText: {
      color: "#ffffff",
      fontSize: 15,
      fontWeight: "700",
    },
    notificationsCard: {
      width: "100%",
      maxHeight: "78%",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
    },
    notificationsHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 6,
    },
    badgeLarge: {
      minWidth: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#ef4444",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 6,
    },
    notificationRow: {
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingVertical: 8,
      paddingLeft: 0,
      paddingRight: 4,
    },
    notificationRowMain: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      minWidth: 0,
      gap: 8,
      paddingRight: 4,
    },
    notificationTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    notificationTrash: {
      alignSelf: "stretch",
      justifyContent: "center",
      paddingHorizontal: 6,
      paddingVertical: 6,
    },
    notificationTrashIcon: {
      fontSize: 18,
    },
    notificationTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
    },
    notificationDetail: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    badgeMini: {
      minWidth: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: "#ef4444",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    fabWrap: {
      position: "absolute",
      right: 12,
      bottom: 78,
      alignItems: "flex-end",
      zIndex: 30,
      ...(Platform.OS === "android" ? { elevation: 20 } : {}),
    },
    fabButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#ff7a00",
      borderWidth: 2,
      borderColor: "#ffd7b0",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 9,
    },
    fabIcon: {
      color: "#ffffff",
      fontSize: 22,
      fontWeight: "700",
    },
    fabMenu: {
      marginBottom: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      overflow: "hidden",
      minWidth: 130,
    },
    fabMenuItem: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    fabMenuText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "600",
    },
  });
}
