import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createForumModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  flex1: { flex: 1 },
  header: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerAction: { color: palette.accent, fontSize: 14, fontWeight: "700" },
  headerTitle: { flex: 1, textAlign: "center", color: palette.text, fontSize: 16, fontWeight: "700" },
  headerGhost: { width: 56 },
  errorBanner: { padding: 10, backgroundColor: "rgba(220,38,38,0.12)" },
  errorTxt: { color: "#fecaca", fontSize: 12, fontWeight: "600", textAlign: "center" },
  listPad: { padding: 14, paddingBottom: 28 },
  listHeader: { marginBottom: 14, gap: 10 },
  listSearchSticky: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
    gap: 8,
  },
  searchLabel: { color: palette.text, fontSize: 13, fontWeight: "700" },
  searchRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  searchInput: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: palette.text,
    fontSize: 15,
    backgroundColor: palette.surface,
  },
  searchBtn: {
    backgroundColor: palette.accent,
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 10,
    justifyContent: "center",
  },
  searchBtnTxt: { color: "#fff", fontSize: 14, fontWeight: "800" },
  clearSearchBtn: { alignSelf: "flex-start" },
  clearSearchTxt: { color: palette.accent, fontSize: 13, fontWeight: "600" },
  emptySearchWrap: { marginTop: 12, gap: 14, alignItems: "center", paddingHorizontal: 8 },
  exampleChipsRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  exampleChip: {
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.45)",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: palette.surface,
  },
  exampleChipTxt: { color: "#93c5fd", fontSize: 17, fontWeight: "800" },
  introBody: { color: palette.textMuted, fontSize: 13, lineHeight: 20 },
  primaryBtn: {
    alignSelf: "flex-start",
    backgroundColor: palette.accent,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  primaryBtnWide: { alignSelf: "stretch" },
  primaryBtnTxt: { color: "#fff", fontSize: 14, fontWeight: "800" },
  topicCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: palette.surface,
  },
  topicHash: { color: "#93c5fd", fontSize: 17, fontWeight: "800" },
  topicMeta: { color: palette.textMuted, fontSize: 12, marginTop: 4 },
  topicHint: { color: palette.accent, fontSize: 12, fontWeight: "700", marginTop: 8 },
  empty: { color: palette.textMuted, fontSize: 13, textAlign: "center", marginTop: 20 },
  centerPad: { padding: 24, alignItems: "center", gap: 8 },
  muted: { color: palette.textMuted, fontSize: 12 },
  formPad: { padding: 16, gap: 10, flexGrow: 1 },
  label: { color: palette.text, fontSize: 13, fontWeight: "700" },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: palette.text,
    fontSize: 15,
    backgroundColor: palette.surface,
  },
  hint: { color: palette.textMuted, fontSize: 12 },
  topicBanner: { paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: palette.border },
  topicBannerHash: { color: "#93c5fd", fontSize: 18, fontWeight: "800" },
  topicBannerSub: { color: palette.textMuted, fontSize: 12, marginTop: 4 },
  topicSaveRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: palette.border,
  },
  topicSaveTxt: { color: palette.textMuted, fontSize: 12, fontWeight: "600" },
  threadPad: { padding: 14, paddingBottom: 8 },
  commentCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    padding: 10,
    backgroundColor: palette.surface,
  },
  commentCardNested: {
    borderColor: "rgba(147, 197, 253, 0.35)",
    backgroundColor: "rgba(30, 41, 59, 0.45)",
  },
  commentHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  commentAuthor: { color: "#93c5fd", fontSize: 13, fontWeight: "700", flex: 1 },
  softDeleteWrap: { paddingVertical: 2, paddingHorizontal: 6 },
  softDeleteText: { color: "rgba(248, 113, 113, 0.85)", fontSize: 12, fontWeight: "600" },
  commentBody: { color: palette.text, fontSize: 14, marginTop: 4, lineHeight: 20 },
  commentDate: { color: palette.textMuted, fontSize: 11, marginTop: 6 },
  metaRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "rgba(148, 163, 184, 0.12)",
  },
  metaIcon: { color: palette.textMuted, fontSize: 14 },
  metaCount: { color: palette.textMuted, fontSize: 12, fontWeight: "600" },
  metaLikeOn: { color: "#fb7185" },
  metaFavOn: { color: "#fbbf24" },
  replyBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: "rgba(59, 130, 246, 0.08)",
  },
  replyBannerTxt: { color: "#93c5fd", fontSize: 13, fontWeight: "600", flex: 1 },
  replyBannerClear: { color: palette.textMuted, fontSize: 16, fontWeight: "700" },
  composer: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
    padding: 10,
    gap: 8,
    backgroundColor: palette.surface,
  },
  composerInput: {
    minHeight: 72,
    maxHeight: 140,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    padding: 10,
    color: palette.text,
    fontSize: 14,
    textAlignVertical: "top",
    backgroundColor: palette.background,
  },
  sendBtn: {
    alignSelf: "flex-end",
    backgroundColor: palette.accent,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
  },
  sendBtnOff: { opacity: 0.7 },
  sendBtnTxt: { color: "#fff", fontSize: 14, fontWeight: "800" },
});
}
