import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createHaberlerModalStyles(colors: ThemePalette) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    closeHit: { minWidth: 64, paddingVertical: 6 },
    closeText: { color: colors.accent, fontSize: 16, fontWeight: "800" },
    headerTitle: { color: colors.text, fontSize: 17, fontWeight: "800" },
    tabGrid: {
      paddingHorizontal: 10,
      paddingVertical: 10,
      gap: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    tabGridRow: { flexDirection: "row", gap: 8 },
    tabCell: {
      flex: 1,
      minHeight: 52,
      paddingVertical: 10,
      paddingHorizontal: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.primaryLight,
      justifyContent: "center",
      alignItems: "center",
    },
    tabCellOn: {
      backgroundColor: colors.accent,
      borderColor: "#ffd7b0",
    },
    tabCellText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: "700",
      textAlign: "center",
      lineHeight: 17,
    },
    tabCellTextOn: { color: "#1e2675" },
    body: { flex: 1 },
    bodyContent: { padding: 14, paddingBottom: 32 },
    block: { marginBottom: 20 },
    sourceTitle: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: "800",
      marginBottom: 8,
    },
    rssLoading: { paddingVertical: 16, alignItems: "center" },
    rssError: { color: colors.textMuted, fontSize: 13, paddingVertical: 8 },
    rssList: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
      backgroundColor: colors.surface,
    },
    articleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    articleTextCol: { flex: 1, paddingRight: 8 },
    articleTitle: { color: colors.text, fontSize: 14, fontWeight: "600" },
    articleMeta: { color: colors.textMuted, fontSize: 11, fontWeight: "600", marginTop: 4 },
    articleChevron: { color: colors.accent, fontSize: 22, fontWeight: "700" },
    tvFullGrid: { paddingTop: 4, gap: 10 },
    tvFullRow: { flexDirection: "row", gap: 8, alignItems: "stretch" },
    tvFullCell: {
      flex: 1,
      minHeight: 56,
      paddingVertical: 12,
      paddingHorizontal: 6,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      justifyContent: "center",
      alignItems: "center",
    },
    tvFullCellText: { color: colors.text, fontSize: 13, fontWeight: "800", textAlign: "center", lineHeight: 17 },
    tvGlobalBottomRow: { justifyContent: "center", gap: 12, paddingHorizontal: 4 },
  });
}

export type HaberlerModalStyles = ReturnType<typeof createHaberlerModalStyles>;
