import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

/** Koyu kuyu (`#0a1040`, `#0b235f`) üzerindeki TextInput placeholder’ları için */
export const harcamalarDeepWellInputPlaceholderColor = "rgba(255, 255, 255, 0.58)";

export function createHarcamalarModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  headerBtn: { minWidth: 52, paddingVertical: 6, paddingHorizontal: 4 },
  headerSpacer: { minWidth: 52, paddingVertical: 6, paddingHorizontal: 4 },
  headerBtnText: { color: palette.text, fontSize: 14, fontWeight: "700" },
  headerCloseText: { color: palette.text, fontSize: 22, fontWeight: "800", textAlign: "right", lineHeight: 24 },
  headerTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  filtreBaslik: { color: "#93c5fd", fontSize: 11, fontWeight: "700", marginBottom: 4 },
  anaTabRow: { flexDirection: "row", gap: 6, paddingHorizontal: 10, paddingTop: 6, paddingBottom: 6 },
  anaTab: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  anaTabOn: { backgroundColor: palette.accent, borderColor: "#ffd7b0", borderWidth: 1.5 },
  anaTabText: { color: palette.textMuted, fontSize: 10, fontWeight: "700", textAlign: "center" },
  anaTabTextOn: { color: "#fff" },
  loader: { flex: 1, justifyContent: "center", alignItems: "center" },
  scroll: { flex: 1 },
  scrollPad: { padding: 14, paddingBottom: 40 },
  ayRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 14 },
  ayBtn: {
    width: 40,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  ayBtnText: { color: palette.text, fontSize: 18, fontWeight: "800" },
  ayKutu: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1f5aa9",
    backgroundColor: "#08245a",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  ayLabel: { color: "#cbd5e1", fontSize: 11, fontWeight: "600" },
  ayValue: { color: "#f8fafc", fontSize: 18, fontWeight: "900", marginTop: 2 },
  ayBugun: {
    paddingHorizontal: 10,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ffd7b0",
    backgroundColor: palette.accent,
    justifyContent: "center",
  },
  ayBugunText: { color: "#fff", fontWeight: "800", fontSize: 12 },
  bolumBaslik: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 12, marginBottom: 8 },
  hint: { color: palette.textMuted, fontSize: 12, lineHeight: 17, marginBottom: 10 },
  gelirGrid: { gap: 10 },
  gelirCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.4)",
    backgroundColor: "#0a1040",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  gelirCardOn: { borderColor: palette.success, borderWidth: 1.5 },
  gelirHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  gelirTitle: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
  kalemAmountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inputInKalemRow: { flex: 1, minWidth: 0, marginBottom: 0 },
  tickBtn: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#0a1040",
  },
  tickBtnText: { color: "#e2e8f0", fontSize: 11, fontWeight: "800" },
  grafikKutu: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    padding: 10,
    backgroundColor: palette.surface,
  },
  grafSatir: { flexDirection: "row", alignItems: "center", marginBottom: 10, gap: 8 },
  grafEtiket: { width: 100, color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  grafTrack: {
    flex: 1,
    height: 22,
    borderRadius: 8,
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    justifyContent: "center",
    overflow: "hidden",
  },
  grafBar: { height: "100%", backgroundColor: palette.accent, borderRadius: 6 },
  grafYok: { marginLeft: 8, color: palette.textMuted, fontSize: 11, fontWeight: "800" },
  grafTutar: { width: 96, textAlign: "right", color: palette.text, fontSize: 11, fontWeight: "800" },
  pastaKutu: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    backgroundColor: palette.surface,
    padding: 10,
    flexDirection: "column",
    gap: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  pastaSag: { width: "100%", gap: 6 },
  pastaSatir: { flexDirection: "row", alignItems: "center", gap: 6, width: "100%" },
  pastaRenk: { width: 10, height: 10, borderRadius: 999 },
  pastaEtiket: { flex: 1, minWidth: 0, color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  pastaPct: { width: 38, textAlign: "right", color: "#93c5fd", fontSize: 11, fontWeight: "800" },
  pastaTutar: { width: 96, textAlign: "right", color: palette.text, fontSize: 11, fontWeight: "800" },
  pastaToplamSatir: {
    marginTop: 4,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(147,197,253,0.35)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pastaToplamEtiket: { color: palette.text, fontSize: 12, fontWeight: "900" },
  pastaToplamTutar: { color: palette.text, fontSize: 12, fontWeight: "900" },
  giderPastaBlok: {
    borderWidth: 1,
    borderColor: "#1d4ed8",
    borderRadius: 12,
    backgroundColor: "#0b235f",
    padding: 10,
    marginTop: 10,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  giderPastaBaslik: { color: "#dbeafe", fontSize: 12, fontWeight: "900", marginBottom: 8 },
  giderChartWrap: { flexDirection: "row", alignItems: "stretch", gap: 8, paddingVertical: 10 },
  giderYAxis: { width: 84, height: 136, justifyContent: "space-between", paddingBottom: 16 },
  giderYAxisRow: { height: 1, justifyContent: "center" },
  giderYAxisText: { color: "#93c5fd", fontSize: 10, fontWeight: "700", textAlign: "right" },
  giderPlotArea: { minHeight: 160, minWidth: 440, justifyContent: "flex-end", position: "relative", paddingBottom: 2 },
  giderGridOverlay: { position: "absolute", left: 0, right: 0, top: 0, bottom: 16, justifyContent: "space-between" },
  giderGridLine: { borderTopWidth: 1, borderTopColor: "rgba(147,197,253,0.22)" },
  giderXAxis: { position: "absolute", left: 0, right: 0, bottom: 16, borderTopWidth: 1.5, borderTopColor: "#60a5fa" },
  giderLegendRow: { position: "absolute", top: -2, right: 0, flexDirection: "row", gap: 12, zIndex: 2 },
  giderLegendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  giderLegendDot: { width: 12, height: 12, borderRadius: 2, borderWidth: 1, borderColor: "#1e3a8a" },
  giderLegendText: { color: "#dbeafe", fontSize: 11, fontWeight: "700" },
  giderBarWrap: { flexDirection: "row", alignItems: "flex-end", gap: 18, paddingTop: 18 },
  giderBarGroup: { alignItems: "center" },
  giderBarPair: { flexDirection: "row", alignItems: "flex-end", gap: 0 },
  giderBarCol: { width: 70, alignItems: "center" },
  giderBarColTight: { width: 38, alignItems: "center" },
  giderBar: {
    width: 30,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderWidth: 1,
    borderColor: "#1e3a8a",
  },
  giderBarTotal: { backgroundColor: "#6366f1" },
  giderBarTxt: { marginTop: 4, color: palette.textMuted, fontSize: 10, fontWeight: "700", textAlign: "center" },
  giderBarVal: { color: "#dbeafe", fontSize: 10, fontWeight: "900", textAlign: "center" },
  giderBarPct: { marginBottom: 4, color: "#fef08a", fontSize: 10, fontWeight: "900" },
  giderGroupLabel: { marginTop: 5, color: "#dbeafe", fontSize: 11, fontWeight: "800", textAlign: "center", width: 84 },
  giderGroupVal: { marginTop: 2, color: "#bfdbfe", fontSize: 10, fontWeight: "800", textAlign: "center", width: 96 },
  label: { color: palette.textMuted, fontSize: 12, marginTop: 8, marginBottom: 4 },
  input: {
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: "#ffffff",
    fontSize: 15,
  },
  inputDisabled: { opacity: 0.5 },
  primaryBtn: {
    marginTop: 14,
    height: 48,
    borderRadius: 12,
    backgroundColor: palette.accent,
    borderWidth: 2,
    borderColor: "#ffd7b0",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  empty: { color: palette.textMuted, fontSize: 13 },
  kayitSatir: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    marginBottom: 8,
  },
  kayitBaslik: { color: palette.text, fontSize: 13, fontWeight: "800" },
  kayitMeta: { color: palette.textMuted, fontSize: 11, marginTop: 2 },
  kayitTutar: { color: palette.text, fontWeight: "900", marginRight: 8 },
  sil: { color: "#fecaca", fontWeight: "800" },
  altTabRow: { gap: 10, marginBottom: 14, paddingVertical: 2 },
  altTab: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    marginRight: 8,
    maxWidth: 160,
    minHeight: 52,
  },
  altTabOn: { borderColor: "#ffd7b0", backgroundColor: palette.accent },
  altTabText: { color: palette.text, fontSize: 13, fontWeight: "800", textAlign: "center" },
  altTabTextOn: { color: "#fff", fontSize: 14, fontWeight: "900" },
  giderGrid: { gap: 10 },
  giderCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.4)",
    backgroundColor: "#0a1040",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  giderTitle: { color: "#ffffff", fontSize: 14, fontWeight: "800", marginBottom: 8 },
  exportRow: { flexDirection: "row", gap: 8, marginBottom: 10 },
  exportRowSectionEnd: { marginTop: 18, marginBottom: 12 },
  saveActionsRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  exportBtn: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  pdfBtn: { backgroundColor: "#dc2626", borderColor: "#fca5a5" },
  excelBtn: { backgroundColor: "#16a34a", borderColor: "#86efac" },
  exportBtnPressed: { transform: [{ scale: 0.97 }], opacity: 0.82 },
  exportBtnText: { color: "#ffffff", fontSize: 13, fontWeight: "900" },
  bankSelectBtn: {
    height: 38,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    justifyContent: "center",
    paddingHorizontal: 10,
    backgroundColor: "#0a1040",
    marginBottom: 8,
  },
  bankSelectBtnText: { color: "#ffffff", fontSize: 12, fontWeight: "700" },
  yokTap: { flexDirection: "row", alignItems: "center", gap: 8, flexShrink: 0 },
  yokBox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.55)",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  yokTick: { color: palette.success, fontSize: 14, fontWeight: "900" },
  yokText: { color: "#ffffff", fontSize: 12, fontWeight: "800" },
  secondaryBtn: {
    marginBottom: 10,
    alignSelf: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#0a1040",
  },
  secondaryBtnText: { color: "#bfdbfe", fontWeight: "800", fontSize: 12 },
  ebitdaUstKutu: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1e3a8a",
    backgroundColor: "#0b235f",
    padding: 10,
    gap: 10,
    marginBottom: 10,
  },
  ebitdaKolon: { borderRadius: 10, borderWidth: 1, borderColor: "#1d4ed8", backgroundColor: "#102967", padding: 8, gap: 4 },
  ebitdaKolonBaslik: { color: "#67e8f9", fontSize: 11, fontWeight: "900" },
  ebitdaSatir: { color: "#dbeafe", fontSize: 11, fontWeight: "700" },
  ebitdaSatirToplam: { color: "#7dd3fc", fontSize: 11, fontWeight: "900", marginTop: 4 },
  ebitdaNot: { color: "#fde68a", fontSize: 10, fontWeight: "700", marginTop: 4 },
  projCol: { width: 92, textAlign: "center" },
  projValue: { textAlign: "right", fontWeight: "800" },
  satirBaslik: { color: "#e2e8f0", fontWeight: "900" },
  ebitdaSatirMavi: { color: "#7dd3fc" },
  toplamCol: { width: 98, textAlign: "right", backgroundColor: "#ea580c", color: "#fff", fontWeight: "900" },
  toplamValue: { color: "#fb923c", fontWeight: "900", textAlign: "right" },
  formulSummary: { minWidth: 520, color: "#93c5fd", fontSize: 11, lineHeight: 16 },
  excelInput: {
    borderWidth: 1,
    borderColor: "#1d4ed8",
    backgroundColor: "#0b235f",
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  rowHighlightIn: {
    borderWidth: 1.5,
    borderColor: "#34d399",
    backgroundColor: "rgba(52, 211, 153, 0.12)",
  },
  rowHighlightOut: {
    borderWidth: 1.5,
    borderColor: "#fb7185",
    backgroundColor: "rgba(251, 113, 133, 0.12)",
  },
  rowHighlightCum: {
    borderWidth: 1.5,
    borderColor: "#facc15",
    backgroundColor: "rgba(250, 204, 21, 0.12)",
  },
  savedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  savedAction: { color: "#93c5fd", fontWeight: "800", fontSize: 12 },
  savedActionDanger: { color: "#fecaca", fontWeight: "900", fontSize: 12 },
  excelRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: palette.border, minWidth: 380 },
  excelH: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    fontWeight: "900",
    color: "#ffffff",
    backgroundColor: "#0a1040",
  },
  excelC: { paddingVertical: 10, paddingHorizontal: 8, color: palette.textMuted, fontSize: 12 },
  excelColKod: { width: 46, textAlign: "center", fontWeight: "800", color: palette.textMuted },
  excelColK: { width: 214 },
  excelColT: { width: 120, textAlign: "right", fontWeight: "800", color: palette.text },
  neg: { color: "#fecaca" },
  pos: { color: palette.success },
  ozetMini: { color: "#bfdbfe", fontSize: 12, marginBottom: 10, fontWeight: "700" },
  filtreRow: { flexDirection: "row", gap: 8, marginBottom: 8 },
  filtreInput: { flex: 1 },
  takvimBtn: { justifyContent: "center", minHeight: 44 },
  takvimValue: { color: "#ffffff", fontSize: 13, fontWeight: "700" },
  takvimPlaceholder: { color: "rgba(255, 255, 255, 0.62)", fontSize: 12, fontWeight: "600" },
  bankModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  bankModalDismiss: { flex: 1 },
  bankModalCard: {
    maxHeight: "72%",
    backgroundColor: palette.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
  },
  bankModalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  bankModalTitle: { color: palette.text, fontSize: 15, fontWeight: "800" },
  bankModalClose: { color: palette.text, fontSize: 20, fontWeight: "700" },
  bankSearch: {
    height: 42,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    color: "#ffffff",
    backgroundColor: "#0a1040",
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  bankList: { maxHeight: 360 },
  bankRow: {
    height: 40,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    justifyContent: "center",
  },
  bankRowText: { color: palette.text, fontSize: 13, fontWeight: "600" },
});
}
