import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createKisiAraModalStyles(colors: ThemePalette) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: "rgba(2,6,23,0.65)",
      justifyContent: "center",
      paddingHorizontal: 14,
    },
    card: {
      flex: 1,
      backgroundColor: colors.surface,
      padding: 12,
    },
    fullscreen: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    title: { color: colors.text, fontSize: 18, fontWeight: "800" },
    headBtns: { flexDirection: "row", alignItems: "center", gap: 8 },
    iconBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    closeTxt: { color: colors.textMuted, fontSize: 14, fontWeight: "700" },
    searchRow: { flexDirection: "row", gap: 8, alignItems: "center" },
    searchFlex: { flex: 1 },
    search: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      backgroundColor: colors.background,
      color: colors.text,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
    },
    searchBtn: {
      minWidth: 72,
      borderRadius: 10,
      paddingVertical: 10,
      alignItems: "center",
      backgroundColor: colors.accent,
    },
    searchBtnTxt: { color: "#fff", fontSize: 15, fontWeight: "800" },
    advancedLink: {
      marginTop: 10,
      color: colors.textMuted,
      textDecorationLine: "underline",
      fontSize: 13,
      fontWeight: "500",
    },
    tabsRow: { marginTop: 10, flexDirection: "row", gap: 8 },
    tabBtn: {
      flex: 1,
      borderRadius: 10,
      paddingVertical: 8,
      alignItems: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tabBtnActive: { backgroundColor: colors.primaryLight, borderColor: colors.accent },
    tabTxt: { color: colors.text, fontSize: 12, fontWeight: "700", textAlign: "center" },
    searchLoadingBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 2,
      marginBottom: 4,
    },
    searchLoadingTxt: { color: colors.textMuted, fontSize: 13, fontWeight: "600" },
    list: { marginTop: 10 },
    listContent: { gap: 8, paddingBottom: 6 },
    row: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.background,
      padding: 9,
      gap: 10,
    },
    personTapArea: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    avatar: { width: 48, height: 48, borderRadius: 24 },
    avatarFallback: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#1e3a8a",
      borderWidth: 1,
      borderColor: "#2563eb",
    },
    avatarInitial: { color: "#dbeafe", fontSize: 18, fontWeight: "700" },
    meta: { flex: 1, minWidth: 0 },
    username: { color: colors.text, fontSize: 15, fontWeight: "700" },
    detail: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    actions: { gap: 6 },
    followBtn: {
      minWidth: 78,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      alignItems: "center",
      backgroundColor: "#2563eb",
    },
    followBtnOn: { backgroundColor: "#16a34a" },
    followBtnPending: { backgroundColor: "#ca8a04" },
    actionBtn: { minWidth: 78, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, alignItems: "center" },
    rejectBtn: { backgroundColor: "#ef4444" },
    followTxt: { color: "#fff", fontSize: 11, fontWeight: "700" },
    msgBtn: {
      minWidth: 78,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      alignItems: "center",
      backgroundColor: colors.accent,
    },
    msgTxt: { color: "#fff", fontSize: 11, fontWeight: "700" },
    disabled: { opacity: 0.6 },
    empty: { textAlign: "center", color: colors.textMuted, marginTop: 14, fontSize: 12 },
    error: { color: "#fca5a5", marginTop: 8, fontSize: 12, fontWeight: "600" },
    advancedCard: {
      maxHeight: "78%",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 12,
    },
    fieldLabel: { color: colors.textMuted, fontSize: 14, fontWeight: "700", marginTop: 6, marginBottom: 4 },
    advancedSearchBtn: {
      marginTop: 14,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: "center",
      backgroundColor: colors.accent,
    },
    advancedSearchTxt: { color: "#fff", fontSize: 16, fontWeight: "800" },
    detailBtn: {
      minWidth: 64,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
    },
    detailBtnTxt: { color: colors.textMuted, fontSize: 12, fontWeight: "700" },
  });
}
