import { StyleSheet, Platform } from "react-native";
import type { ThemePalette } from "../theme/palettes";

/** `#0a1040` kuyu alanlarında TextInput placeholder */
export const kredilerDeepWellPlaceholderColor = "rgba(255, 255, 255, 0.58)";

export function createKredilerModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  headerBtn: { paddingVertical: 6, paddingHorizontal: 4, minWidth: 72 },
  headerBtnText: { color: palette.text, fontSize: 15, fontWeight: "600" },
  closeX: { color: palette.text, fontSize: 22, fontWeight: "400", textAlign: "right" },
  headerTitle: { color: palette.text, fontSize: 17, fontWeight: "700" },
  tabRow: {
    flexDirection: "row",
    marginHorizontal: 12,
    marginTop: 10,
    gap: 8,
    backgroundColor: palette.surface,
    borderRadius: 12,
    padding: 6,
    borderWidth: 1,
    borderColor: palette.border,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnActive: { backgroundColor: palette.accent },
  tabBtnText: { color: palette.textMuted, fontSize: 11, fontWeight: "600", textAlign: "center" },
  tabBtnTextActive: { color: "#ffffff" },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  sectionHint: { color: palette.textMuted, fontSize: 12, lineHeight: 17, marginBottom: 14 },
  subTitle: { color: palette.text, fontSize: 15, fontWeight: "700", marginTop: 8, marginBottom: 8 },
  label: { color: palette.textMuted, fontSize: 12, marginBottom: 4, marginTop: 10 },
  input: {
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: "#ffffff",
    fontSize: 16,
  },
  inputPressable: {
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 14,
    justifyContent: "center",
    minHeight: 48,
  },
  inputPressableText: { color: "#ffffff", fontSize: 16 },
  inputPressablePlaceholder: { color: "rgba(255, 255, 255, 0.58)", fontSize: 16 },
  inputNoLabelTop: { marginTop: 10 },
  /** Tam 2 satır: üstte 3, altta 3 — yatay dizilim */
  chipRowThree: {
    flexDirection: "row",
    flexWrap: "nowrap",
    width: "100%",
    gap: 8,
    alignItems: "stretch",
  },
  chipRowGap: { marginTop: 8 },
  chipFlex: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  chipInGrid: {
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  bankModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  bankModalDismiss: { ...StyleSheet.absoluteFillObject, zIndex: 0 },
  bankModalCard: {
    zIndex: 1,
    backgroundColor: palette.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    maxHeight: "82%",
    paddingBottom: Platform.OS === "ios" ? 24 : 16,
  },
  bankModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  bankModalTitle: { color: palette.text, fontSize: 17, fontWeight: "700" },
  bankModalClose: { color: palette.textMuted, fontSize: 20, padding: 4 },
  bankSearch: {
    marginHorizontal: 16,
    marginVertical: 10,
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#ffffff",
    fontSize: 15,
  },
  bankList: { flexGrow: 0, maxHeight: 420 },
  bankRow: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.border,
  },
  bankRowText: { color: palette.text, fontSize: 15 },
  bankEmpty: { color: palette.textMuted, padding: 20, textAlign: "center", fontSize: 14 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#0a1040",
  },
  chipOn: { backgroundColor: palette.primaryLight, borderColor: "#ffd7b0" },
  chipText: { color: "rgba(255, 255, 255, 0.9)", fontSize: 12, fontWeight: "600" },
  chipTextGrid: { fontSize: 11, textAlign: "center", width: "100%" },
  chipTextOn: { color: "#ffffff" },
  disclaimer: { color: palette.textMuted, fontSize: 11, marginTop: 12, lineHeight: 16 },
  primaryBtn: {
    marginTop: 18,
    backgroundColor: palette.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffd7b0",
  },
  primaryBtnText: { color: "#ffffff", fontSize: 16, fontWeight: "700" },
  listeKaydetBtn: {
    marginTop: 16,
    backgroundColor: palette.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffd7b0",
  },
  secondaryBtn: { marginTop: 12, paddingVertical: 10, alignItems: "center" },
  secondaryBtnText: { color: palette.accent, fontSize: 14, fontWeight: "600" },
  exportRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  exportBtn: {
    flex: 1,
    backgroundColor: palette.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ffd7b0",
    minHeight: 44,
  },
  exportBtnSecondary: {
    backgroundColor: "#0a1040",
    borderColor: palette.border,
  },
  exportBtnDisabled: { opacity: 0.65 },
  exportBtnText: { color: "#ffffff", fontSize: 14, fontWeight: "700" },
  exportBtnTextSecondary: { color: palette.accent },
  resultCard: {
    marginTop: 20,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
  },
  resultBig: { color: palette.text, fontSize: 18, fontWeight: "800", marginVertical: 8 },
  resultLine: { color: palette.text, fontSize: 14, marginTop: 4 },
  resultMuted: { color: palette.textMuted },
  planTableScroll: {
    marginTop: 12,
    maxHeight: 360,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: "#0a1040",
  },
  planTableContent: { paddingBottom: 8 },
  planHeaderRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.2)", paddingBottom: 6 },
  planHCell: { width: 88, color: "rgba(255, 255, 255, 0.72)", fontSize: 11, fontWeight: "700" },
  planRow: { flexDirection: "row", paddingVertical: 4 },
  planCell: { width: 88, color: "#ffffff", fontSize: 11 },
  emptyText: { color: palette.textMuted, fontSize: 14, marginTop: 12 },
  loanCard: {
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#0a1040",
  },
  loanCardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  loanBank: { color: "#ffffff", fontSize: 16, fontWeight: "700", flex: 1 },
  loanSil: { color: "rgba(255, 255, 255, 0.75)", fontSize: 14, fontWeight: "600" },
  loanMeta: { color: palette.accent, fontSize: 13, marginTop: 4 },
  loanLine: { color: "rgba(255, 255, 255, 0.88)", fontSize: 13, marginTop: 4 },
  loanDate: { color: "rgba(255, 255, 255, 0.65)", fontSize: 11, marginTop: 8 },
});
}
