import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createMesajlarimModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  header: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerAction: { color: palette.accent, fontSize: 14, fontWeight: "700" },
  headerTitle: { color: palette.text, fontSize: 16, fontWeight: "700" },
  headerMiniBtn: { minWidth: 74, alignItems: "flex-end" },
  headerMiniBtnText: { color: palette.accent, fontSize: 12, fontWeight: "700" },
  content: { flex: 1, paddingHorizontal: 8, paddingVertical: 10, gap: 10 },
  searchInput: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.surface,
    color: palette.text,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
    fontSize: 14,
  },
  composeKeyboardWrap: { flex: 1 },
  composeScroll: { flex: 1 },
  composeScrollContent: { flexGrow: 1, paddingBottom: 12 },
  composeToolbarWrap: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.surface,
    paddingTop: 10,
    paddingHorizontal: 10,
  },
  composeToolbarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 10,
  },
  composeCard: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: 12,
    padding: 8,
  },
  label: { color: palette.textMuted, marginBottom: 6, fontSize: 12, fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.background,
    color: palette.text,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 14,
  },
  textArea: { minHeight: 120, textAlignVertical: "top" },
  hintWrap: { flexDirection: "row", flexWrap: "wrap", marginBottom: 8, gap: 6 },
  hintChip: { backgroundColor: "#1f2937", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  hintChipText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  iconGrid: { marginTop: 2, alignItems: "flex-end", gap: 6 },
  iconRow2: { flexDirection: "row", alignItems: "center", gap: 8 },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.background,
  },
  iconBtnText: { fontSize: 17 },
  sendSlimBtn: {
    minWidth: 48,
    minHeight: 48,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    elevation: 4,
  },
  sendSlimText: { color: "#fff", fontSize: 18, fontWeight: "800" },
  sendBtnDisabled: { opacity: 0.5 },
  attachPreview: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  attachPreviewColumn: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
  },
  attachThumbRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    justifyContent: "space-between",
  },
  attachPreviewText: { color: palette.text, fontSize: 12, fontWeight: "600" },
  embedPreviewImage: { width: 64, height: 64, borderRadius: 8 },
  attachActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  attachRemove: { color: palette.accent, fontSize: 12, fontWeight: "700" },
  attachAdd: { color: "#22c55e", fontSize: 12, fontWeight: "700" },
  recordingText: { color: "#f87171", fontSize: 12, fontWeight: "700", marginTop: 6 },
  emojiPanel: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    padding: 8,
    backgroundColor: palette.background,
  },
  emojiCell: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  emojiText: { fontSize: 20 },
  errorText: { color: "#fca5a5", marginTop: 8, fontSize: 12, fontWeight: "600" },
  listWrap: { flex: 1 },
  listContent: { paddingBottom: 20, gap: 8 },
  loadingWrap: { paddingTop: 24, alignItems: "center" },
  loadingText: { marginTop: 8, color: palette.textMuted, fontSize: 12 },
  emptyText: { color: palette.textMuted, textAlign: "center", marginTop: 18 },
  msgMeta: { color: palette.textMuted, fontSize: 11, marginTop: 4 },
  msgCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.surface,
    padding: 10,
  },
  msgTopRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  msgAvatarWrap: { width: 54, height: 54, borderRadius: 27, overflow: "hidden", marginTop: 1 },
  msgAvatarImage: { width: "100%", height: "100%" },
  msgAvatarFallback: {
    width: "100%",
    height: "100%",
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1e3a8a",
    borderWidth: 1,
    borderColor: "#2563eb",
  },
  msgAvatarInitial: { color: "#dbeafe", fontSize: 20, fontWeight: "700" },
  msgMain: { flex: 1 },
  msgHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  msgHeaderRight: { flexDirection: "row", alignItems: "center", gap: 6 },
  msgUnreadBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  msgUnreadBadgeText: { color: "#fff", fontSize: 10, fontWeight: "700" },
  msgTo: { color: palette.textMuted, fontSize: 16, fontWeight: "700" },
  msgAt: { color: palette.textMuted, fontSize: 11 },
  msgBody: { color: palette.text, fontSize: 14, lineHeight: 20 },
  msgFooterRow: { marginTop: 4, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  deleteConvBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(239,68,68,0.18)",
  },
  deleteConvText: { color: "#f87171", fontSize: 14, fontWeight: "700" },
  chatWrap: { flex: 1 },
  /** Sohbet: liste + alt gönder satırı tek sütunda; FlatList tek başına flex:1 olunca Android’de footer taşabiliyor. */
  chatColumn: { flex: 1, flexDirection: "column", minHeight: 0 },
  chatList: { flex: 1, minHeight: 0 },
  chatLoadingHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginBottom: 4,
  },
  chatLoadingHeaderText: { color: palette.textMuted, fontSize: 12 },
  bubble: {
    maxWidth: "86%",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
  },
  bubbleMine: {
    alignSelf: "flex-end",
    backgroundColor: "#2647b8",
    borderColor: "#3f66e8",
  },
  bubblePeer: {
    alignSelf: "flex-start",
    backgroundColor: "#1b2d73",
    borderColor: "#2f4ea8",
  },
  bubbleText: { color: palette.text, fontSize: 14, lineHeight: 20 },
  bubbleAt: { color: palette.textMuted, fontSize: 10, marginTop: 4 },
  msgImage: { width: 190, height: 190, borderRadius: 8, marginBottom: 6 },
  videoBadge: { color: "#fcd34d", fontSize: 12, fontWeight: "700", marginBottom: 4 },
  audioChip: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 6,
    backgroundColor: palette.background,
    minWidth: 170,
  },
  audioTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  audioChipText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  audioTime: { color: palette.textMuted, fontSize: 11, fontWeight: "600" },
  audioProgressTrack: {
    marginTop: 6,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#334155",
    overflow: "hidden",
  },
  audioProgressFill: { height: "100%", backgroundColor: "#22c55e", borderRadius: 999 },
  chatComposer: { flexDirection: "row", alignItems: "flex-end", gap: 8, paddingTop: 6 },
  chatInput: { flex: 1, marginBottom: 0, minHeight: 84, textAlignVertical: "top" },
  /** FlatList ile aynı sütunda: üstte flex:1 liste, altta hep görünür; aksi halde liste tüm yüksekliği alıp gönder tuşunu ekran dışına iter. */
  chatFooter: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 8,
    paddingTop: 6,
    zIndex: 20,
    elevation: 22,
  },
  zoomOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.95)", justifyContent: "center", alignItems: "center" },
  zoomImage: { width: "100%", height: "100%" },
  zoomCloseBtn: { position: "absolute", top: 52, right: 20, zIndex: 5, backgroundColor: "rgba(0,0,0,0.6)", borderRadius: 16 },
  zoomCloseText: { color: "#fff", fontSize: 20, paddingHorizontal: 10, paddingVertical: 4 },
});
}
