import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createSocialProfileModalStyles(palette: ThemePalette) {
  return StyleSheet.create({

  overlay: { flex: 1, backgroundColor: palette.surface },
  card: {
    flex: 1,
    backgroundColor: palette.surface,
    padding: 14,
  },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  title: { color: palette.text, fontSize: 20, fontWeight: "800" },
  iconBtn: {
    width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center",
    backgroundColor: palette.background, borderWidth: 1, borderColor: palette.border,
  },
  iconBtnTxt: { color: palette.accent, fontSize: 14, fontWeight: "700" },
  closeTxt: { color: palette.textMuted, fontSize: 14, fontWeight: "700" },
  top: { alignItems: "center", marginBottom: 10 },
  avatar: { width: 92, height: 92, borderRadius: 46, marginBottom: 8 },
  avatarFallback: {
    width: 92, height: 92, borderRadius: 46, alignItems: "center", justifyContent: "center", marginBottom: 8,
    backgroundColor: "#1e3a8a", borderWidth: 1, borderColor: "#2563eb",
  },
  avatarInitial: { color: "#dbeafe", fontSize: 30, fontWeight: "800" },
  avatarPrivacyGlyph: { fontSize: 44 },
  privacyLoading: { flex: 1, justifyContent: "center", alignItems: "center", paddingTop: 48 },
  privacyMsg: { color: palette.textMuted, fontSize: 15, lineHeight: 23, paddingHorizontal: 8, paddingTop: 16 },
  username: { color: palette.text, fontSize: 24, fontWeight: "800" },
  name: { color: palette.textMuted, fontSize: 16, marginTop: 3 },
  actionRow: { marginTop: 2, marginBottom: 8, flexDirection: "row", gap: 8, justifyContent: "center" },
  syncHintRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 6,
    marginBottom: 4,
  },
  syncHintTxt: { color: palette.textMuted, fontSize: 12, fontWeight: "600" },
  messageBtn: { backgroundColor: "#2563eb", borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12 },
  followBtn: { backgroundColor: palette.accent, borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12 },
  followPending: { backgroundColor: "#ca8a04" },
  followOn: { backgroundColor: "#16a34a" },
  blockBtn: { backgroundColor: "#ef4444", borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12 },
  unblockBtn: { backgroundColor: "#16a34a" },
  btnTxt: { color: "#fff", fontSize: 12, fontWeight: "800" },
  line: { color: palette.text, fontSize: 15, marginTop: 8, fontWeight: "600" },
  content: { marginTop: 10, flex: 1 },
  empty: { color: palette.textMuted, fontSize: 14, marginTop: 8 },
  sectionTitle: { color: palette.text, fontSize: 16, fontWeight: "800", marginTop: 12, marginBottom: 8 },
  headTabsRow: {
    marginTop: 2,
    marginBottom: 6,
    gap: 6,
  },
  headTabsLine: {
    flexDirection: "row",
    gap: 6,
    alignItems: "stretch",
  },
  headTabBtn: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.surface,
    paddingHorizontal: 4,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
  },
  headTabBtnActive: {
    backgroundColor: palette.accent,
    borderColor: "#ffd7b0",
  },
  headTabTxt: { color: "#ffffff", fontSize: 10, fontWeight: "700", textAlign: "center", width: "100%" },
  sectionWrap: { gap: 8 },
  infoRow: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  infoLabel: { color: palette.textMuted, fontSize: 12, fontWeight: "700", marginBottom: 2 },
  infoValue: { color: palette.text, fontSize: 15, fontWeight: "700" },
  bulletCard: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  bulletTxt: { color: palette.text, fontSize: 14, fontWeight: "600" },
  feedCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.background,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  feedTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 4 },
  feedUserWrap: { flexDirection: "row", alignItems: "center", gap: 7, flex: 1 },
  feedAvatar: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: palette.border, backgroundColor: "#10204f" },
  feedAvatarFallback: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "#1e3a8a",
    alignItems: "center",
    justifyContent: "center",
  },
  feedAvatarInitial: { color: "#dbeafe", fontSize: 11, fontWeight: "800" },
  feedDate: { color: palette.textMuted, fontSize: 10, fontWeight: "600" },
  feedHead: { color: "#93c5fd", fontSize: 12, fontWeight: "700", marginBottom: 4 },
  feedBody: { color: palette.text, fontSize: 14, lineHeight: 20 },
  feedMediaImage: { marginTop: 8, width: "100%", height: 190, borderRadius: 10, borderWidth: 1, borderColor: palette.border },
  feedMediaVideo: { marginTop: 8, width: "100%", height: 220, borderRadius: 10, backgroundColor: "#000" },
  feedMediaVideoWrap: { position: "relative" },
  feedMediaVideoOverlay: {
    position: "absolute",
    top: 8,
    right: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    backgroundColor: "rgba(2,6,23,0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  feedMediaVideoOverlayTxt: { color: "#fff", fontSize: 11, fontWeight: "700" },
  fullscreenSafe: { flex: 1, backgroundColor: palette.background },
  fullscreenHeader: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fullscreenTitle: { color: palette.text, fontSize: 16, fontWeight: "700" },
  fullscreenBody: { flex: 1, padding: 12 },
  fullscreenUser: { color: palette.text, fontSize: 15, fontWeight: "800" },
  fullscreenDate: { marginTop: 4, color: palette.textMuted, fontSize: 12 },
  fullscreenText: { marginTop: 10, color: palette.text, fontSize: 16, lineHeight: 24 },
  fullscreenMediaImage: { marginTop: 12, width: "100%", height: 320, borderRadius: 12, borderWidth: 1, borderColor: palette.border },
  fullscreenMediaVideo: { marginTop: 12, width: "100%", height: 320, borderRadius: 12, backgroundColor: "#000" },
  mediaViewerOverlay: { flex: 1, backgroundColor: "rgba(2,6,23,0.96)", alignItems: "center", justifyContent: "center", padding: 16 },
  mediaViewerImage: { width: "100%", height: "85%" },
  mediaViewerCloseBtn: {
    position: "absolute",
    bottom: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "rgba(2,6,23,0.6)",
  },
  mediaViewerCloseTxt: { color: "#fff", fontSize: 13, fontWeight: "700" },
  mediaViewerVideo: { flex: 1, backgroundColor: "#000" },
  feedMetaRow: { marginTop: 8, flexDirection: "row", gap: 8, alignItems: "center", flexWrap: "wrap" },
  feedMetaPill: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    alignItems: "center",
    justifyContent: "center",
  },
  feedMetaIcon: { color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  feedLikePill: { borderColor: "#ef4444", backgroundColor: "rgba(239,68,68,0.12)" },
  feedLikeTxt: { color: "#fca5a5" },
  feedFavPill: { borderColor: "#facc15", backgroundColor: "rgba(250,204,21,0.14)" },
  feedFavTxt: { color: "#fde68a" },
  feedActionRow: { marginTop: 8, flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  feedActionBtn: {
    width: 34,
    height: 32,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  feedEditBtn: { backgroundColor: "#2563eb" },
  feedDeleteBtn: { backgroundColor: "#dc2626" },
  feedSaveBtn: { backgroundColor: "#16a34a" },
  feedCancelBtn: { backgroundColor: "#64748b" },
  feedActionTxt: { color: "#fff", fontSize: 14, fontWeight: "800" },
  feedEditInput: {
    marginTop: 4,
    minHeight: 78,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.surface,
    color: palette.text,
    paddingHorizontal: 8,
    paddingVertical: 7,
    textAlignVertical: "top",
    fontSize: 13,
  },
  threadComposer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: "rgba(2,6,23,0.45)",
    borderRadius: 10,
    padding: 8,
    gap: 6,
  },
  threadTitle: { color: palette.textMuted, fontSize: 12, fontWeight: "700" },
  threadInput: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.surface,
    color: palette.text,
    paddingHorizontal: 8,
    paddingVertical: 7,
    textAlignVertical: "top",
    fontSize: 13,
  },
  threadSendBtn: {
    alignSelf: "flex-end",
    borderRadius: 8,
    backgroundColor: palette.accent,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  threadSendTxt: { color: "#fff", fontSize: 12, fontWeight: "700" },
  repliesWrap: { marginTop: 10, gap: 6 },
  replyBubble: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: "rgba(2,6,23,0.35)",
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  replyMeta: { color: palette.textMuted, fontSize: 11, marginBottom: 3 },
  replyText: { color: palette.text, fontSize: 12, lineHeight: 17 },
  replyActionsRow: { marginTop: 8, flexDirection: "row", gap: 6 },
  replyActionPill: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: palette.background,
  },
  replyActionTxt: { color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  mediaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  mediaCell: {
    width: "31%",
    aspectRatio: 1,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.background,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    padding: 6,
  },
  mediaImg: { width: "100%", height: "100%" },
  mediaFallback: { fontSize: 30, color: palette.textMuted },
  mediaMini: { marginTop: 4, color: palette.textMuted, fontSize: 10 },
  videoListWrap: { gap: 14, marginTop: 4 },
  inlineVideoCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    backgroundColor: palette.background,
    padding: 10,
    gap: 8,
  },
  inlineVideoTitle: { color: palette.text, fontSize: 13, fontWeight: "700" },
  inlineVideo: { width: "100%", height: 220, borderRadius: 10, backgroundColor: "#000" },
  inlineVideoControls: { flexDirection: "row", justifyContent: "center", gap: 8, flexWrap: "wrap" },
  inlineVideoBtn: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  inlineVideoBtnTxt: { color: palette.text, fontSize: 12, fontWeight: "700" },
  countsRow: { flexDirection: "row", gap: 8, marginTop: 8 },
  countItem: { alignItems: "center", minWidth: 56 },
  countNum: { color: palette.text, fontSize: 16, fontWeight: "800" },
  countLbl: { color: palette.textMuted, fontSize: 12, fontWeight: "600" },
  });
}
