import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createYatirimModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  headerBtn: { minWidth: 64 },
  headerBtnText: { color: palette.text, fontSize: 15, fontWeight: "700", textAlign: "right" },
  headerTitle: { color: palette.text, fontSize: 17, fontWeight: "800" },
  tabRow: { flexDirection: "row", gap: 8, padding: 12 },
  tabBtn: { flex: 1, borderWidth: 1, borderColor: palette.border, borderRadius: 10, paddingVertical: 10, alignItems: "center", backgroundColor: palette.surface },
  tabOn: { backgroundColor: palette.accent, borderColor: "#ffd7b0" },
  tabText: { color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  tabTextOn: { color: "#fff" },
  scroll: { flex: 1 },
  content: { padding: 14, paddingBottom: 36 },
  label: { color: palette.textMuted, fontSize: 12, marginBottom: 4, marginTop: 8 },
  input: {
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: palette.text,
    fontSize: 15,
  },
  inputPressable: {
    backgroundColor: "#0a1040",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  inputPressableText: { color: palette.text, fontSize: 15 },
  filterRow: { flexDirection: "row", gap: 8 },
  flex: { flex: 1 },
  row: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 },
  totalText: { color: palette.textMuted, fontWeight: "700" },
  totalVal: { color: palette.text, fontWeight: "900" },
  primaryBtn: {
    marginTop: 12,
    backgroundColor: palette.accent,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ffd7b0",
    alignItems: "center",
    paddingVertical: 12,
  },
  primaryBtnText: { color: "#fff", fontWeight: "800", fontSize: 14 },
  sectionTitle: { color: palette.text, fontSize: 14, fontWeight: "900", marginTop: 14, marginBottom: 8 },
  tableCard: {
    backgroundColor: palette.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 10,
  },
  tableHead: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: palette.border, paddingBottom: 8, marginBottom: 2 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.08)", paddingVertical: 8 },
  cellH: { color: "#dbeafe", fontSize: 11, fontWeight: "800" },
  cell: { color: palette.text, fontSize: 11 },
  cDate: { width: 70 },
  cUrun: { flex: 1, minWidth: 90, paddingRight: 8 },
  cNum: { width: 64, textAlign: "right" },
  iosDateWrap: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
    backgroundColor: palette.surface,
    paddingBottom: 8,
  },
  iosDateHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  iosDateTitle: { color: palette.textMuted, fontSize: 13, fontWeight: "600" },
  iosDateDone: { color: palette.accent, fontSize: 14, fontWeight: "800" },
  summaryCard: {
    marginTop: 10,
    backgroundColor: "#0a1040",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
  },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 4 },
  summaryLabel: { color: palette.textMuted, fontSize: 13, fontWeight: "700" },
  summaryValue: { color: palette.text, fontSize: 14, fontWeight: "900" },
});
}
