import type { ImageStyle, TextStyle, ViewStyle } from "react-native";
import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export type YorumYazModalCompiledStyles = {
  readonly [key: string]: ViewStyle | TextStyle | ImageStyle;
};

export function createYorumYazModalStyles(colors: ThemePalette): YorumYazModalCompiledStyles {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    header: {
      height: 52,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    headerAction: { color: colors.accent, fontSize: 14, fontWeight: "700" },
    headerTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
    headerGhost: { width: 36 },
    content: { flex: 1 },
    keyboardCol: { flex: 1 },
    scrollInner: { flexGrow: 1, paddingHorizontal: 12, paddingTop: 12, paddingBottom: 8 },
    composeFooter: {
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingTop: 10,
      zIndex: 20,
      elevation: 22,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    composeFooterLeft: { flex: 1, justifyContent: "center", minHeight: 44, paddingRight: 6 },
    composeFooterActions: { flexDirection: "row", alignItems: "center", gap: 10 },
    sendingHint: { color: colors.textMuted, fontSize: 13, fontWeight: "600" },
    textArea: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: 10,
      alignSelf: "stretch",
      minHeight: 190,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: colors.text,
      fontSize: 14,
      textAlignVertical: "top",
    },
    counter: { marginTop: 6, color: colors.textMuted, fontSize: 11, textAlign: "right" },
    mediaPreview: {
      marginTop: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    mediaImage: { width: 74, height: 74, borderRadius: 8 },
    mediaVideo: { color: colors.text, fontSize: 12, fontWeight: "700" },
    mediaActionRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    mediaRemove: { color: "#f87171", fontSize: 12, fontWeight: "700" },
    mediaAdd: { color: "#34d399", fontSize: 12, fontWeight: "700" },
    mediaAttachedBox: {
      marginTop: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    mediaAttachedTxt: { color: colors.textMuted, fontSize: 12, fontWeight: "600" },
    mediaAttachedCard: {
      alignSelf: "stretch",
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      borderRadius: 12,
      overflow: "hidden",
    },
    /* width set in component via useWindowDimensions (ScrollView + % issues on some RN builds) */
    mediaPreviewFull: { height: 220, backgroundColor: colors.background },
    mediaVideoPreview: { height: 220, backgroundColor: "#000" },
    mediaAttachedMeta: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 10,
      paddingVertical: 10,
      gap: 8,
    },
    mediaAttachedLbl: { flex: 1, color: colors.textMuted, fontSize: 12, fontWeight: "600" },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    sendIconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    sendIconBtnBusy: { opacity: 0.92 },
    sendBtnDisabled: { opacity: 0.6 },
    iconTxt: { color: "#fff", fontSize: 18, fontWeight: "800" },
    iconTxtDark: { color: colors.text, fontSize: 18, fontWeight: "800" },
    errorText: { color: "#fca5a5", marginTop: 8, fontSize: 12, fontWeight: "600" },
  }) as unknown as YorumYazModalCompiledStyles;
}
