import { Platform, StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createLoginScreenStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: palette.background,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  container: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerBlock: {
    paddingTop: 6,
    paddingBottom: 4,
    width: "100%",
    alignItems: "center",
  },
  brand: {
    fontSize: 26,
    fontWeight: "700",
    color: palette.text,
    letterSpacing: 0.5,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    color: palette.textMuted,
    textAlign: "center",
  },
  logo: {
    marginTop: 10,
    marginBottom: 14,
    alignSelf: "center",
    width: 120,
    height: 120,
    borderRadius: 16,
  },
  form: {
    backgroundColor: palette.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
  },
  segmentContainer: {
    flexDirection: "row",
    backgroundColor: palette.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 4,
    gap: 6,
  },
  modeContainer: {
    marginTop: 8,
    marginBottom: 8,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  segmentActive: {
    backgroundColor: palette.primary,
  },
  segmentText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  segmentTextActive: {
    color: "#ffffff",
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: palette.text,
  },
  labelSpacing: {
    marginTop: 8,
  },
  input: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 10 : 8,
    fontSize: 14,
    color: palette.text,
    backgroundColor: palette.background,
  },
  inlineRow: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.background,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  checkmark: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 14,
  },
  inlineLabel: {
    color: palette.text,
    fontSize: 13,
  },
  inlineLabelWrap: {
    color: palette.text,
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  linkSmall: {
    fontSize: 13,
    color: palette.text,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  robotBox: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: palette.background,
  },
  robotBoxChecked: {
    borderColor: palette.accent,
  },
  robotLabel: {
    fontSize: 14,
    color: palette.text,
    fontWeight: "600",
    flex: 1,
  },
  robotMeta: {
    fontSize: 12,
    color: palette.textMuted,
    fontWeight: "600",
  },
  privacyRow: {
    marginTop: 8,
  },
  linkWrapLeft: {
    marginTop: 8,
    alignItems: "flex-start",
  },
  link: {
    fontSize: 13,
    color: palette.text,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  errorText: {
    marginTop: 8,
    color: palette.error,
    fontSize: 12,
    fontWeight: "600",
  },
  primaryButton: {
    marginTop: 10,
    backgroundColor: palette.accent,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonPressed: {
    opacity: 0.9,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  disclaimerText: {
    marginTop: 10,
    fontSize: 10,
    lineHeight: 14,
    color: palette.textMuted,
    textAlign: "center",
  },
  footerSiteText: {
    marginTop: 16,
    paddingTop: 6,
    marginBottom: 12,
    fontSize: 14,
    color: palette.textMuted,
    textAlign: "center",
    fontWeight: "600",
    fontStyle: "italic",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: palette.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: palette.text,
    marginBottom: 12,
  },
  modalInfo: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 6,
  },
  modalInput: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: palette.text,
    backgroundColor: palette.background,
  },
  captchaFrame: {
    height: 220,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: palette.surface,
  },
  modalButton: {
    marginTop: 12,
    backgroundColor: palette.primary,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 14,
  },
  modalLink: {
    marginTop: 10,
    alignItems: "center",
  },
  modalLinkText: {
    color: palette.textMuted,
    textDecorationLine: "underline",
  },
  resetInfo: {
    marginTop: 8,
    fontSize: 12,
    color: palette.textMuted,
    lineHeight: 18,
  },
});
}
