import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createPiyasalarModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  pad: { minWidth: 44, alignItems: "center" },
  title: { color: palette.text, fontSize: 17, fontWeight: "800" },
  close: { color: palette.text, fontSize: 22 },
  tabRowSplit: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 6,
  },
  tabRowTop: {
    flexDirection: "row",
    gap: 8,
  },
  tabRowBottom: {
    flexDirection: "row",
    gap: 6,
    marginTop: 8,
  },
  tabBtnPressed: { opacity: 0.88 },
  tabBtnHalf: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.surface,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnThird: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.surface,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnQuarter: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.surface,
    paddingVertical: 7,
    paddingHorizontal: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  tabTextQuarter: { color: palette.textMuted, fontSize: 10, fontWeight: "700" },
  tabBtnOn: { backgroundColor: palette.accent, borderColor: "#ffd7b0" },
  tabText: { color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  tabTextOn: { color: "#fff" },
  content: { paddingHorizontal: 12, paddingTop: 8, paddingBottom: 12 },
  listBody: { flex: 1, minHeight: 0 },
  listFlex: { flex: 1, minHeight: 0 },
  contentFlat: { paddingHorizontal: 12, paddingTop: 8, paddingBottom: 12, flexGrow: 1 },
  gridRow3: { justifyContent: "space-between" },
  searchInput: {
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    color: palette.text,
    paddingHorizontal: 12,
    marginBottom: 10,
    fontSize: 13,
    fontWeight: "600",
  },
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 8, alignItems: "stretch" },
  cardWrap: { width: "48%", alignSelf: "stretch" },
  cardWrapBist: { width: "31.5%", alignSelf: "stretch" },
});
}
