import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createPortfoyumModalStyles(palette: ThemePalette) {
  const PF_DEEP = palette.background;
  const PF_CARD = palette.surface;
  const PF_BAND = palette.surface;
  const onLightBg = palette.background === "#ffffff";
  /** Alt satır / genişleyen işlemlerde karttan hafif ayrım */
  const PF_SUB_SCRIM = onLightBg ? "#e2e8f0" : "rgba(15,23,42,0.35)";

  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: PF_DEEP },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: PF_CARD,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  headerPad: { minWidth: 44, alignItems: "center" },
  title: { color: palette.text, fontSize: 17, fontWeight: "800" },
  close: { color: palette.text, fontSize: 22 },
  tabRow: { flexDirection: "row", gap: 8, paddingHorizontal: 14, paddingTop: 10 },
  tabBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: PF_BAND,
    alignItems: "center",
    paddingVertical: 10,
  },
  tabBtnOn: { backgroundColor: palette.accent, borderColor: "#ffd7b0" },
  tabText: { color: palette.textMuted, fontSize: 12, fontWeight: "700" },
  tabTextOn: { color: "#fff" },
  filterRow: { flexDirection: "row", gap: 8, paddingHorizontal: 14, paddingTop: 10 },
  filterColumn: { paddingHorizontal: 14, paddingTop: 10 },
  filterBlockTitle: { color: palette.text, fontSize: 13, fontWeight: "800" },
  filterBlockTitleSpaced: { marginTop: 14 },
  filterHelp: { color: palette.textMuted, fontSize: 11, marginTop: 4, lineHeight: 15 },
  singleDayPick: { marginTop: 8, borderRadius: 12, paddingVertical: 12 },
  rangeRow: { flexDirection: "row", alignItems: "flex-end", gap: 8, marginTop: 8 },
  rangeItem: { flex: 1, minWidth: 0 },
  rangeHint: { color: palette.textMuted, fontSize: 10, fontWeight: "700", marginBottom: 4 },
  rangeDateBtn: { borderRadius: 12, paddingVertical: 11 },
  rangeDash: { color: palette.text, fontSize: 18, fontWeight: "800", paddingBottom: 10 },
  filterYearWrap: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
    alignItems: "flex-start",
  },
  filterYearCol: { width: 88 },
  filterYearRangeCol: { flex: 1, minWidth: 0 },
  yilInputWide: { width: "100%", marginTop: 8, borderRadius: 12, paddingVertical: 11 },
  input: {
    backgroundColor: PF_BAND,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    color: palette.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    justifyContent: "center",
  },
  yilInput: { width: 96 },
  ayInput: { flex: 1 },
  flexInput: { flex: 1 },
  ayText: { color: palette.text, fontSize: 14, fontWeight: "600" },
  scroll: { flex: 1, backgroundColor: PF_DEEP },
  content: { padding: 14, paddingBottom: 28 },
  pfEmpty: { color: palette.textMuted, fontSize: 14, textAlign: "center", marginVertical: 20 },
  pfCard: {
    backgroundColor: PF_CARD,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: 12,
    overflow: "hidden",
  },
  pfCardTop: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 8 },
  pfCardTitleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  pfSymbol: { color: palette.text, fontSize: 16, fontWeight: "900", flex: 1, marginRight: 8 },
  pfTopValue: { color: palette.text, fontSize: 16, fontWeight: "800" },
  pfOrtMaliyet: { color: palette.textMuted, fontSize: 12, fontWeight: "700", marginTop: 6 },
  pfPnlRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  pfPnlPct: { fontSize: 13, fontWeight: "800" },
  pfPnlTl: { fontSize: 12, fontWeight: "700" },
  pfBarOuter: {
    height: 8,
    borderRadius: 4,
    backgroundColor: onLightBg ? "rgba(13,21,88,0.15)" : "rgba(255,255,255,0.18)",
    marginTop: 10,
    overflow: "hidden",
  },
  pfBarInner: { height: 8, backgroundColor: "#60a5fa", borderRadius: 4 },
  pfBarPct: { color: palette.textMuted, fontSize: 11, fontWeight: "700", marginTop: 4 },
  pfCardBand: {
    flexDirection: "row",
    backgroundColor: PF_BAND,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  pfBandCol: { flex: 1, minWidth: 0, paddingHorizontal: 4 },
  pfBandLabel: { color: palette.textMuted, fontSize: 10, fontWeight: "700", marginBottom: 4 },
  pfBandVal: { color: palette.text, fontSize: 12, fontWeight: "800" },
  pfAnlikInput: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    textAlign: "right",
    backgroundColor: "#0f172a",
  },
  pfKurHint: { color: palette.textMuted, fontSize: 9, marginTop: 4 },
  pfCardActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  pfExpandHit: { flexDirection: "row", alignItems: "center" },
  pfChevron: { color: palette.text, fontSize: 12, fontWeight: "800", marginRight: 6 },
  pfDetayTxt: { color: palette.text, fontSize: 12, fontWeight: "600" },
  pfSilGrup: { color: "#fb7185", fontSize: 12, fontWeight: "800" },
  pfSubRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: palette.border,
    backgroundColor: PF_SUB_SCRIM,
  },
  pfSubLeft: { flex: 1, minWidth: 0 },
  pfSubDate: { color: palette.text, fontSize: 12, fontWeight: "700" },
  pfSubMeta: { color: palette.textMuted, fontSize: 11, marginTop: 2 },
  pfSubActions: { flexDirection: "row", gap: 10, alignItems: "center" },
  editBtn: { color: "#4ade80", fontSize: 16 },
  delBtn: { color: "#fb7185", fontSize: 16 },
  summaryCard: {
    marginTop: 4,
    backgroundColor: PF_CARD,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 14,
    padding: 14,
  },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5 },
  summaryLabel: { color: palette.textMuted, fontWeight: "700", fontSize: 13, flex: 1, marginRight: 8 },
  summaryValue: { color: palette.text, fontWeight: "900", fontSize: 13 },
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  menuCard: {
    maxHeight: 360,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
  },
  menuItem: {
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.border,
  },
  menuText: { color: palette.text, fontSize: 14 },
  iosWrap: { backgroundColor: palette.surface, borderTopWidth: 1, borderTopColor: palette.border },
  iosHead: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 12, paddingTop: 8 },
  iosDone: { color: palette.accent, fontSize: 14, fontWeight: "800" },
  bottomActions: { flexDirection: "row", gap: 8, marginTop: 12 },
  bottomBtn: {
    flex: 1,
    backgroundColor: palette.accent,
    borderColor: "#ffd7b0",
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
  },
  pdfBtn: { backgroundColor: "#b91c1c", borderColor: "#fca5a5" },
  bottomBtnText: { color: "#fff", fontSize: 12, fontWeight: "800" },
  savedCard: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    maxHeight: 420,
    width: "90%",
    padding: 12,
    gap: 8,
  },
  savedTitle: { color: palette.text, fontSize: 15, fontWeight: "800", marginBottom: 4 },
  savedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.border,
    paddingVertical: 8,
  },
  savedMain: { flex: 1 },
  savedName: { color: palette.text, fontSize: 13, fontWeight: "700" },
  savedMeta: { color: palette.textMuted, fontSize: 11, marginTop: 2 },
});
}
