import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

/** ProfilimModal + iç içe FeedSection / yardımcı bileşenler */
export function createProfilimModalStyles(colors: ThemePalette) {
  return StyleSheet.create({

  safe: { flex: 1, backgroundColor: colors.background },
  header: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
  headerAction: { color: colors.accent, fontSize: 14, fontWeight: "700" },
  headerActionDisabled: { opacity: 0.45 },
  scroll: { flex: 1 },
  content: { padding: 14, paddingBottom: 30 },
  avatarCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    alignItems: "center",
  },
  avatarCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#3b3f7a",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  avatarText: { color: "#fff", fontSize: 28, fontWeight: "800" },
  avatarImage: { width: 84, height: 84, borderRadius: 42 },
  profileNameText: { color: colors.text, fontSize: 16, fontWeight: "700" },
  profileNameRow: { minHeight: 22, justifyContent: "center", alignItems: "center", marginBottom: 2 },
  selfProfileTap: { alignItems: "center" },
  bioText: { marginTop: 6, color: colors.textMuted, fontSize: 13, textAlign: "center" },
  socialStatsRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 4,
    gap: 8,
  },
  socialStatItem: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 6,
    alignItems: "center",
    backgroundColor: colors.background,
  },
  socialStatValue: { color: colors.text, fontSize: 15, fontWeight: "800" },
  socialStatLabel: { color: colors.textMuted, fontSize: 11, marginTop: 2, textAlign: "center" },
  socialCardFull: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: 12,
  },
  socialHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  socialCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  socialCloseTxt: { color: colors.textMuted, fontSize: 14, fontWeight: "700" },
  socialTabs: { flexDirection: "row", gap: 6, marginBottom: 8 },
  socialTabBtn: {
    flex: 1,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingVertical: 7,
    alignItems: "center",
  },
  socialTabBtnActive: { backgroundColor: "#2d6cdf", borderColor: "#4f87f2" },
  socialTabTxt: { color: colors.text, fontSize: 11, fontWeight: "700" },
  socialSearchInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.background,
    color: colors.text,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 13,
    marginBottom: 8,
  },
  socialEmpty: { color: colors.textMuted, textAlign: "center", marginTop: 14, marginBottom: 10 },
  socialRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  socialAvatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1e3a8a",
    borderWidth: 1,
    borderColor: "#2563eb",
    overflow: "hidden",
  },
  socialAvatarImg: { width: "100%", height: "100%" },
  socialAvatarInitial: { color: "#dbeafe", fontSize: 16, fontWeight: "700" },
  socialMeta: { flex: 1 },
  socialUser: { color: colors.text, fontSize: 14, fontWeight: "700" },
  socialSub: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  avatarButtons: { width: "100%", gap: 8 },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: colors.background,
  },
  secondaryBtnDisabled: { opacity: 0.55 },
  careerActionRow: { flexDirection: "row", gap: 8, marginTop: 8, marginBottom: 2 },
  careerSaveBtn: { flex: 1, backgroundColor: "#0d6a38", borderColor: "#34d399" },
  careerDeleteBtn: { flex: 1, backgroundColor: "#7f1d1d", borderColor: "#f87171" },
  secondaryBtnText: { color: colors.text, fontSize: 13, fontWeight: "600" },
  infoRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
    padding: 10,
    marginBottom: 8,
  },
  infoLabel: { color: colors.textMuted, fontSize: 12, marginBottom: 4 },
  infoValue: { color: colors.text, fontSize: 14, fontWeight: "600" },
  sectionTitle: { color: colors.text, fontSize: 15, fontWeight: "700", marginTop: 12, marginBottom: 8 },
  fieldWrap: { marginBottom: 12 },
  label: { color: colors.textMuted, marginBottom: 6, fontSize: 12, fontWeight: "600" },
  requiredStar: { color: "#ef4444", fontSize: 12, fontWeight: "800" },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  textArea: {
    minHeight: 74,
    textAlignVertical: "top",
  },
  selectBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  selectText: { color: colors.text, fontSize: 14, fontWeight: "600" },
  selectHint: { color: colors.textMuted, marginTop: 4, fontSize: 11 },
  cityOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "center", padding: 20 },
  cityCard: {
    maxHeight: "70%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  cityTitle: { color: colors.text, fontSize: 15, fontWeight: "700", paddingHorizontal: 12, paddingVertical: 10 },
  cityRow: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  cityRowText: { color: colors.text, fontSize: 14, fontWeight: "600" },
  webLikeSections: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    padding: 10,
    gap: 4,
  },
  webLikeTitle: { color: colors.text, fontSize: 14, fontWeight: "800", marginTop: 6 },
  webLikeTxt: { color: colors.textMuted, fontSize: 13, fontWeight: "600" },
  sectionWrap: { gap: 8, marginTop: 8 },
  feedCard: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.background,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  feedUser: { color: "#93c5fd", fontSize: 12, fontWeight: "700", marginBottom: 4 },
  feedText: { color: colors.text, fontSize: 13, lineHeight: 18 },
  mediaGridMine: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  mediaImgMine: { width: "31%", aspectRatio: 1, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  photoViewerOverlay: {
    flex: 1,
    backgroundColor: "rgba(2,6,23,0.95)",
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  photoViewerImg: { width: "100%", height: "88%" },
  photoViewerCloseBtn: {
    position: "absolute",
    top: 52,
    right: 16,
    zIndex: 10,
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  photoViewerCloseTxt: { color: colors.text, fontSize: 16, fontWeight: "800" },
  feedMetaRow: { marginTop: 8, flexDirection: "row", gap: 8, alignItems: "center", flexWrap: "wrap" },
  feedMetaPill: {
    minHeight: 28,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  feedMetaIcon: { color: colors.textMuted, fontSize: 11, fontWeight: "700" },
  feedLikePill: { borderColor: "#ef4444", backgroundColor: "rgba(239,68,68,0.12)" },
  feedLikeTxt: { color: "#fca5a5" },
  feedFavPill: { borderColor: "#facc15", backgroundColor: "rgba(250,204,21,0.14)" },
  feedFavTxt: { color: "#fde68a" },
  threadComposer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(2,6,23,0.45)",
    borderRadius: 10,
    padding: 8,
    gap: 6,
  },
  threadTitle: { color: colors.textMuted, fontSize: 12, fontWeight: "700" },
  threadInput: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: 8,
    paddingVertical: 7,
    textAlignVertical: "top",
    fontSize: 13,
  },
  threadSendBtn: {
    alignSelf: "flex-end",
    borderRadius: 8,
    backgroundColor: colors.accent,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  threadSendTxt: { color: "#fff", fontSize: 12, fontWeight: "700" },
  repliesWrap: { marginTop: 10, gap: 6 },
  replyBubble: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "rgba(2,6,23,0.5)",
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  replyMeta: { color: colors.textMuted, fontSize: 10, marginBottom: 2 },
  replyText: { color: colors.text, fontSize: 12, lineHeight: 17 },
  replyActionsRow: { marginTop: 8, flexDirection: "row", gap: 6 },
  replyActionPill: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: colors.background,
  },
  replyActionTxt: { color: colors.textMuted, fontSize: 11, fontWeight: "700" },
  feedTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 4 },
  feedUserWrap: { flexDirection: "row", alignItems: "center", gap: 7, flex: 1 },
  feedAvatar: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: "#10204f" },
  feedAvatarFallback: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#1e3a8a",
    alignItems: "center",
    justifyContent: "center",
  },
  feedAvatarInitial: { color: "#dbeafe", fontSize: 11, fontWeight: "800" },
  feedDate: { color: colors.textMuted, fontSize: 10, fontWeight: "600" },
  feedActionRow: { marginTop: 8, flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  feedActionBtn: {
    width: 34,
    height: 32,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  feedEditBtn: { backgroundColor: "#2563eb" },
  feedDeleteBtn: { backgroundColor: "#dc2626" },
  feedSaveBtn: { backgroundColor: "#16a34a" },
  feedCancelBtn: { backgroundColor: "#64748b" },
  feedActionTxt: { color: "#fff", fontSize: 14, fontWeight: "800" },
  feedEditInput: {
    marginTop: 4,
    minHeight: 78,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: 8,
    paddingVertical: 7,
    textAlignVertical: "top",
    fontSize: 13,
  },
  feedMediaImage: { marginTop: 8, width: "100%", height: 190, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  feedMediaVideoBadge: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "rgba(15,23,42,0.45)",
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  feedMediaVideoTxt: { color: colors.textMuted, fontSize: 12, fontWeight: "700" },
  feedMediaVideo: {
    marginTop: 8,
    width: "100%",
    height: 220,
    borderRadius: 10,
    backgroundColor: "#000",
  },
  feedMediaVideoWrap: { position: "relative" },
  feedMediaVideoOverlay: {
    position: "absolute",
    top: 8,
    right: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    backgroundColor: "rgba(2,6,23,0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  feedMediaVideoOverlayTxt: { color: "#fff", fontSize: 11, fontWeight: "700" },
  fullscreenSafe: { flex: 1, backgroundColor: colors.background },
  fullscreenHeader: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fullscreenBody: { flex: 1, padding: 12 },
  fullscreenUser: { color: colors.text, fontSize: 15, fontWeight: "800" },
  fullscreenDate: { marginTop: 4, color: colors.textMuted, fontSize: 12 },
  fullscreenText: { marginTop: 10, color: colors.text, fontSize: 16, lineHeight: 24 },
  fullscreenMediaImage: { marginTop: 12, width: "100%", height: 320, borderRadius: 12, borderWidth: 1, borderColor: colors.border },
  fullscreenMediaVideo: { marginTop: 12, width: "100%", height: 320, borderRadius: 12, backgroundColor: "#000" },
  mediaViewerOverlay: { flex: 1, backgroundColor: "rgba(2,6,23,0.96)", alignItems: "center", justifyContent: "center", padding: 16 },
  mediaViewerImage: { width: "100%", height: "85%" },
  mediaViewerCloseBtn: {
    position: "absolute",
    bottom: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "rgba(2,6,23,0.6)",
  },
  mediaViewerCloseTxt: { color: "#fff", fontSize: 13, fontWeight: "700" },
  mediaViewerVideo: { flex: 1, backgroundColor: "#000" },
  inlineVideoCard: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.background,
    padding: 8,
    gap: 8,
  },
  inlineVideo: { width: "100%", height: 220, borderRadius: 10, backgroundColor: "#000" },
  inlineVideoControls: { flexDirection: "row", justifyContent: "center", gap: 8 },
  inlineVideoBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  inlineVideoBtnTxt: { color: colors.text, fontSize: 12, fontWeight: "700" },
  profileTabsWrap: {
    marginBottom: 10,
    gap: 6,
  },
  profileTabsLine: { flexDirection: "row", gap: 6, alignItems: "stretch" },
  profileTabBtn: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#0f1f5d",
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
  },
  profileTabBtnActive: {
    backgroundColor: colors.accent,
    borderColor: "#ffd7b0",
  },
  profileTabTxt: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "center",
    width: "100%",
  },

    loadingWrap: { flex: 1, justifyContent: "center", alignItems: "center", paddingVertical: 24 },
    loadingText: { color: colors.textMuted, fontSize: 13, fontWeight: "600" },
    headerGhost: { width: 64 },
  });
}
