import { Platform, StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createSiteAyarlarModalStyles(c: ThemePalette, isLight: boolean) {
  const activeTint = isLight ? "rgba(255, 109, 0, 0.1)" : "rgba(255, 109, 0, 0.14)";
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: c.background },
    flex: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      backgroundColor: c.surface,
    },
    headerTitles: { flex: 1, paddingRight: 12 },
    title: { color: c.text, fontSize: 26, fontWeight: "800" },
    subtitle: { color: c.accent, fontSize: 15, fontWeight: "700", marginTop: 4 },
    closeSq: {
      width: 40,
      height: 40,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.background,
    },
    closeSqTxt: { color: c.text, fontSize: 18, fontWeight: "700" },
    scrollContent: { padding: 16, paddingBottom: 40 },
    menuHeading: { color: c.textMuted, fontSize: 12, fontWeight: "800", marginBottom: 10, letterSpacing: 0.4 },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 8,
      backgroundColor: c.surface,
    },
    menuItemActive: {
      borderColor: c.accent,
      borderWidth: 2,
      backgroundColor: activeTint,
    },
    menuItemTxt: { color: c.text, fontSize: 15, fontWeight: "700", flex: 1 },
    detailBox: { marginTop: 22 },
    detailTitle: { color: c.text, fontSize: 20, fontWeight: "800", marginBottom: 10 },
    detailHint: { color: c.textMuted, fontSize: 13, lineHeight: 20, marginBottom: 14 },
    privacyCard: {
      flexDirection: "row",
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 14,
      padding: 14,
      marginBottom: 10,
      backgroundColor: c.surface,
    },
    privacyCardActive: { borderColor: c.accent, borderWidth: 2 },
    privacyIcon: { fontSize: 28, marginTop: 2, marginRight: 12 },
    privacyTxtCol: { flex: 1 },
    privacyTitle: { color: c.text, fontSize: 16, fontWeight: "800" },
    privacyBody: { color: c.textMuted, fontSize: 12, lineHeight: 18, marginTop: 6 },
    fieldLbl: { color: c.textMuted, fontSize: 13, fontWeight: "600", marginTop: 10, marginBottom: 6 },
    inp: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: Platform.OS === "ios" ? 12 : 10,
      color: c.text,
      backgroundColor: c.surface,
      fontSize: 15,
    },
    langRow: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      padding: 14,
      marginBottom: 8,
      backgroundColor: c.surface,
    },
    langRowActive: { borderColor: c.accent, borderWidth: 2 },
    langFlag: { fontSize: 26, marginRight: 12 },
    langTxtCol: { flex: 1 },
    langTr: { color: c.text, fontSize: 15, fontWeight: "800" },
    langNative: { color: c.textMuted, fontSize: 12, marginTop: 2 },
    themeRow: {
      flexDirection: "row",
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 14,
      padding: 14,
      marginBottom: 10,
      backgroundColor: c.surface,
    },
    themeRowActive: { borderColor: c.accent, borderWidth: 2 },
    themeIcon: { fontSize: 26, marginRight: 12 },
    themeTxtCol: { flex: 1 },
    themeTitle: { color: c.text, fontSize: 16, fontWeight: "800" },
    themeSub: { color: c.textMuted, fontSize: 12, lineHeight: 18, marginTop: 4 },
    saveRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 16 },
    saveBtn: {
      backgroundColor: c.primaryLight,
      paddingHorizontal: 22,
      paddingVertical: 12,
      borderRadius: 12,
      minWidth: 100,
      alignItems: "center",
    },
    saveBtnDisabled: { opacity: 0.65 },
    saveBtnTxt: { color: c.text, fontWeight: "800", fontSize: 15 },
  });
}
