import { StyleSheet } from "react-native";
import type { ThemePalette } from "../theme/palettes";

export function createYorumlarimModalStyles(palette: ThemePalette) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  header: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerAction: { color: palette.accent, fontSize: 14, fontWeight: "700" },
  headerTitle: { color: palette.text, fontSize: 16, fontWeight: "700" },
  headerGhost: { width: 36 },
  content: { flex: 1, paddingHorizontal: 10, paddingTop: 10, paddingBottom: 2 },
  loadingWrap: { alignItems: "center", marginTop: 24 },
  loadingText: { marginTop: 8, color: palette.textMuted, fontSize: 12 },
  listContent: { paddingBottom: 20, gap: 8 },
  card: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8, gap: 8 },
  author: { color: "#93c5fd", fontSize: 13, fontWeight: "700" },
  date: { color: palette.textMuted, fontSize: 11 },
  commentText: { color: palette.text, fontSize: 14, lineHeight: 20 },
  mediaImg: { width: "100%", height: 190, borderRadius: 10, marginTop: 10 },
  mediaVideoBadge: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.background,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mediaVideoTxt: { color: palette.text, fontSize: 12, fontWeight: "700" },
  mediaVideo: {
    marginTop: 10,
    width: "100%",
    height: 220,
    borderRadius: 10,
    backgroundColor: "#000",
  },
  mediaVideoWrap: { position: "relative" },
  mediaVideoOverlay: {
    position: "absolute",
    top: 10,
    right: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    backgroundColor: "rgba(2,6,23,0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mediaVideoOverlayTxt: { color: "#fff", fontSize: 11, fontWeight: "700" },
  fullscreenSafe: { flex: 1, backgroundColor: palette.background },
  fullscreenHeader: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fullscreenBody: { flex: 1, padding: 12 },
  fullscreenUser: { color: palette.text, fontSize: 15, fontWeight: "800" },
  fullscreenDate: { marginTop: 4, color: palette.textMuted, fontSize: 12 },
  fullscreenText: { marginTop: 10, color: palette.text, fontSize: 16, lineHeight: 24 },
  fullscreenMediaImage: { marginTop: 12, width: "100%", height: 320, borderRadius: 12, borderWidth: 1, borderColor: palette.border },
  fullscreenMediaVideo: { marginTop: 12, width: "100%", height: 320, borderRadius: 12, backgroundColor: "#000" },
  mediaViewerOverlay: { flex: 1, backgroundColor: "rgba(2,6,23,0.96)", alignItems: "center", justifyContent: "center", padding: 16 },
  mediaViewerImage: { width: "100%", height: "85%" },
  mediaViewerCloseBtn: {
    position: "absolute",
    bottom: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "rgba(2,6,23,0.6)",
  },
  mediaViewerCloseTxt: { color: "#fff", fontSize: 13, fontWeight: "700" },
  mediaViewerVideo: { flex: 1, backgroundColor: "#000" },
  editInput: {
    minHeight: 90,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.background,
    color: palette.text,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
  },
  rowActions: { marginTop: 10, flexDirection: "row", justifyContent: "flex-end", gap: 8 },
  actionBtn: {
    width: 38,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 0,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  actionText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  socialRow: { marginTop: 10, flexDirection: "row", flexWrap: "wrap", gap: 8 },
  socialBtnIcon: {
    minWidth: 42,
    height: 32,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 16,
    paddingHorizontal: 7,
    backgroundColor: palette.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  socialBtnLikeActive: { borderColor: "#ef4444", backgroundColor: "rgba(239,68,68,0.12)" },
  socialBtnFavActive: { borderColor: "#facc15", backgroundColor: "rgba(250,204,21,0.14)" },
  socialIcon: { color: palette.text, fontSize: 14, fontWeight: "800", lineHeight: 16 },
  socialIconLikeActive: { color: "#ef4444" },
  socialIconFavActive: { color: "#facc15" },
  socialCount: { color: palette.textMuted, fontSize: 10, fontWeight: "700", marginTop: 1 },
  socialCountLikeActive: { color: "#fca5a5" },
  socialCountFavActive: { color: "#fde68a" },
  quoteBox: {
    borderLeftWidth: 3,
    borderLeftColor: "#60a5fa",
    backgroundColor: "rgba(15,23,42,0.45)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginBottom: 8,
  },
  quoteMeta: { color: "#93c5fd", fontSize: 11, fontWeight: "700", marginBottom: 2 },
  quoteText: { color: palette.textMuted, fontSize: 12, lineHeight: 16 },
  inlineComposer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.background,
    padding: 8,
  },
  inlineTitle: { color: palette.textMuted, fontSize: 12, fontWeight: "700", marginBottom: 6 },
  inlineInput: {
    minHeight: 68,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.surface,
    color: palette.text,
    paddingHorizontal: 8,
    paddingVertical: 6,
    textAlignVertical: "top",
    fontSize: 13,
  },
  inlineSendBtn: {
    marginTop: 8,
    alignSelf: "flex-end",
    borderRadius: 8,
    backgroundColor: palette.accent,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  inlineSendText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  repliesWrap: { marginTop: 10, gap: 6 },
  replyBubble: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: "rgba(2,6,23,0.5)",
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  replyMeta: { color: palette.textMuted, fontSize: 10, marginBottom: 2 },
  replyText: { color: palette.text, fontSize: 12, lineHeight: 17 },
  replyActionsRow: { marginTop: 8, flexDirection: "row", gap: 6 },
  replyActionPill: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: palette.background,
  },
  replyActionTxt: { color: palette.textMuted, fontSize: 11, fontWeight: "700" },
  editBtn: { backgroundColor: "#2563eb" },
  deleteBtn: { backgroundColor: "#dc2626" },
  saveBtn: { backgroundColor: "#16a34a" },
  cancelBtn: { backgroundColor: "#64748b" },
  emptyText: { marginTop: 18, textAlign: "center", color: palette.textMuted, fontSize: 13 },
  errorText: { marginTop: 8, color: "#fca5a5", fontSize: 12, fontWeight: "600" },
});
}
